/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hhfgosfpnnsrhofhrqgq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZmdvc2Zwbm5zcmhvZmhycWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTM5NjIsImV4cCI6MjA3NjM4OTk2Mn0.koSfEsc24-fIrcHkShthNDWJhujxZ8fX6G-4QM5peI8"